### ISSUE TITLE
Update api.data.gov/metrics

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#179]
http://api.data.gov/metrics/

**Comment by GUI** [comment]
The metrics are updated: http://api.data.gov/metrics/ It finally pulls them from a live API endpoint, so this should stay up to date for good now (although, we cache the results for around 6 hours, so there's a bit of a delay, and I'm also rounding some of the bigger numbers, so you won't see hits going up all the time). The only bit of remaining static information the page is the agency count. I don't think we can really determine that automatically, so we will probably want to periodically revisit that.

Hopefully that does the trick, but feel free to reopen if you spot any issues or would like to tweak anything.

**Comment by GUI** [comment]
I just made one additional tweak to the analytics numbers on this page. The API traffic numbers now only count successful responses. It lowers our numbers a bit, but I think this is probably a better count.

This excludes most of the random bot traffic that crawls our site, over-rate-limit error responses, as well as requests made while an API backend might be down. It also means we're excluding API requests that legitimately return something like a 404 Not Found error, which in one sense is a real API request (since it's hitting the API backend), but for these metric purposes, I think excluding all error responses is probably be the easiest thing. But let me know if anyone feels differently.
