### ISSUE TITLE
metrics page breaks when in http

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#222]
http://api.data.gov/metrics/ shows this:  

![screen shot 2015-04-30 at 7 11 47 pm](https://cloud.githubusercontent.com/assets/633088/7424240/08410d3e-ef6d-11e4-9d99-8303ffdf4404.png)

**Comment by GUI** [comment]
Oops, thanks for spotting that. It should be fixed now.

This got broken due to some of our HTTPS requirements. We had forced all our internal API Umbrella APIs to be loaded over HTTPS (which includes the metrics API call this makes), but I forgot this page was loading things via whatever protocol you loaded the page on. I've made the quick fix to force this call to HTTPS to fix things. (Although, more generally, https://github.com/18F/api.data.gov/issues/211 would also help rectify this type of possibility, but that requires a bit more investigation).
