### ISSUE TITLE
encourage program specific demo-keys 

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#258]
Since the common `demo-key` key is being used in so many places, it runs out more quickly.  

Better to encourage some programs who are comfortable to migrate to using a demo key specific to them.

**Comment by GUI** [comment]
Just to clarify, the `DEMO_KEY` is rate limited [by IP address](http://api.data.gov/docs/rate-limits/#demokey-rate-limits) which generally means that it's rate limited on a per-user basis, rather than globally. So if you're getting over rate limit errors this actually doesn't mean everyone else is seeing the same errors when using `DEMO_KEY`. It's designed this way to try to encourage individuals to get their own key when they start bumping into limits without affecting unrelated users exploring the app. 

The main caveat is that since this limiting is done on a per IP basis, it's not always exactly per-user, particularly in large organizations where multiple users might be exploring the API documentation or using the demo key. For example, here at NREL most of our external traffic appears to come from a single IP address so even though I might not personally be exceeding the `DEMO_KEY` rate limits, I do occasionally hit the limits due to other users within our organization making enough `DEMO_KEY` requests on a given day.

Are you personally bumping into these over rate limit issues a lot, or have you heard this from other people? If it's been other people, has it been predominantly 18F/GSA co-workers? If GSA's network is setup similar to NREL's (all traffic appearing to come from a single IP), then that would likely explain the issues, but again, these overages would only be affecting your organization's IP and not other external users or organizations. But obviously this still isn't quite ideal if lots of agencies operate this way. We could look into raising the `DEMO_KEY` limits. Or there's other more account-ish things we could explore to try and make it easier to use your own personal key while looking at docs rather than always using the demo key (since I have my own key, I'm just often lazy and follow the doc links using `DEMO_KEY`). OpenFDA does something simple that's sort of in this vein where they remember your current key with a browser cookie.

Also, it's worth noting that with some of [recent changes](https://github.com/NREL/api-umbrella-gatekeeper/pull/19/files) @cmc333333 made, I believe the `DEMO_KEY` should actually be operating with per-agency limits now, as long as each agency is using their own domain name (so `DEMO_KEY` requests against FDA and NASA would be counted differently for example). We might need to double check this is working this way for these IP-based key limits, but our changes there were intended to bucket the usage against each agency's domain separately, which should give us agency specific limits without needing different keys.

**Comment by gbinal** [comment]
We've started using multiple demo keys as well, so should be good here.  Closing.
