### ISSUE TITLE
Consider a higher default rate limit

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#297]
We get enough requests that it may be worth having the default be higher.

**Comment by GUI** [comment]
Each agency can setup higher default limits for their own APIs: https://github.com/18F/api.data.gov/wiki/User-Manual:-Agencies#setting-your-apis-default-rate-limits So maybe we should be re-iterating this when we forward on requests about rate limits?

But we can also implement a higher default limit out of the gate for new APIs, if we want. I think we'd just want to be careful to not impact our existing APIs that are relying on the current system-wide defaults without checking with agencies first. Or we could set explicit 1,000 per hour limits on all the existing APIs so those wouldn't be impacted by a change to our system-wide default.

1,000 per hour was a pretty arbitrary number we picked a while ago, so we can certainly tweak it. Although, from just my personal perspective, I think it still seems like a fairly decent and generous default without us knowing more about how the APIs are being used or what kind of resource demands the API requests impose on the agencies. But if we find most agencies are down with higher limits by default, then that would be nice for everyone involved (less support requests and more freedom for users). Should we maybe poll our existing agencies to get their opinions? Or should we try out a higher default for all new APIs and see what new agencies think?

**Comment by cmc333333** [comment]
I agree with @GUI -- there'd be some negative unintended consequences if we were to bumping up the defaults. For example, we already have agencies which hit a _backend_ rate limit (i.e. their resources cannot handle the requests). Popping up the rate limits would exacerbate that problem substantially.

I'm under the impression that we've only been getting more requests to bump up rate limits because we have more users. I would bet that the percentage of users aren't having any problems with their limits has remained relatively constant. If anything, I think this is more incentive to get out of the inbox business and let agencies field these requests.

**Comment by gbinal** [comment]
Cool.  Sounds good.  

> If anything, I think this is more incentive to get out of the inbox business and let agencies field these requests.

Yeah - let's pick that up.
