### ISSUE TITLE
Missing API Key page renders with html tags showing

### ISSUE THREAD

**Issue by TheLastQuestion** [18F/api.data.gov#366]
Tried an ED api without including a key, the resulting page failed to interpret the html. It displayed tags and all as:

```
<h1>API KEY MISSING</h1>

<hr>College Scorecard requires an API Key for access. <br><br>To obtain a key, visit <a href="https://api.data.gov/signup">https://api.data.gov/signup</a>.<br><br> You will receive an email with your key. When you receive this key, simply append it to your API requests with the additional parameter &api_key=xxxxxxxxxxxxx.
```

**Comment by gbinal** [comment]
Thanks for the heads up, @TheLastQuestion.  

I see what you're referring to [here](https://api.data.gov/ed/collegescorecard/).  It's an oddity that I think has to do with how the website is set up as opposed to how the api error is being passed through.  Though the presence of the formatting is a bit strange to see like that, it looks like it's returning the error message effectively.   

This is an oddity that is worth addressing at some point though.  I'll add to the backlog.

**Comment by GUI** [comment]
@TheLastQuestion: This HTML formatting should no longer be showing up. Sorry for the long response, but thanks for the heads up!

For the api.data.gov's team reference: This was only affecting the College Scorecard API, due to some customization to the error messages on their specific API backend. Other API backends were not affected in a similar way.
