### ISSUE TITLE
Report of API keys not arriving 

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#402]
https://github.com/GSA/data.gov/issues/799

From @brownpl: 

> I field some support requests for the College Scorecard and recently we've gotten a few from users that have not received the email containing their API key. My colleague and I have attempted to register a few keys ourselves [here](https://api.data.gov/signup/) to both our corporate addresses and our gmail accounts and we have also not received them in our inbox or junk mail folders.

**Comment by gbinal** [comment]
I just tried registering and haven't gotten mine yet.

**Comment by LindsayYoung** [comment]
I got a report of this too, I was really confused because they had their account number but not their key.

**Comment by GUI** [comment]
Thanks for the heads up, and sorry for the problems!

@gbinal, @LindsayYoung: I'm deploying a fix shortly. Any preferences on whether we deliver the backlog of messages that failed to be sent earlier? We stopped sending e-mails on 8/31, so if we deliver the full backlog, some users might wonder why they're suddenly getting a signup e-mail a week late, but everyone would get their keys.

**Comment by LindsayYoung** [comment]
My preference would be to give them keys. 

I just got another report on this too. 

Thanks for fixing!

**Comment by gbinal** [comment]
Update: it just arrived for me.

**Comment by gbinal** [comment]
@gui - we think all of the backlog will go out?

**Comment by GUI** [comment]
This should be fixed now. The full backlog of e-mails has also been sent out (so any users that signed up in the past week and didn't get an e-mail should have just gotten one).

Sorry for the trouble, but thanks to everyone for alerting us to the issue.

@gbinal: This was also catching the support e-mails to us, which of course are people saying they didn't receive their e-mail. Oops. :( They should have received their API key, but I'll also respond to all those support e-mails.

For more technical details on what caused this, we made a security fix last week that changed one of our internal configuration settings for the default hostname of our system. This inadvertently broke our ability to send outgoing e-mail since without this default hostname setting, the e-mails we sent were coming form "noreply@localhost" instead of "noreply@api.data.gov." AWS SES was rejecting these localhost e-mails since they were from an unknown domain. So the fix to set an explicit hostname just for the e-mails was relatively straightforward (https://github.com/18F/api.data.gov-ops/commit/52c237f45cd9be008286b36bd3ef45509b5c07e3), it's just unfortunate we didn't catch this earlier.

One thing we could do to better track this would be to setup monitoring around our e-mail queue size, and if failures grow in the queue, that's probably a good sign that our outbound e-mails are failing. We're in the midst of some broader system changes for the api.data.gov platform, so I'm not sure it makes sense to setup this monitoring now (since how we would monitor things will change), but I think we can definitely try to get better monitoring setup around this once we migrate our systems.

**Comment by GUI** [comment]
@LindsayYoung: Oh, and a slight tangential note, but to clarify the mystery around the user having their account ID, but not an API key: We always create the API key and account immediately on signup, but if the account requires e-mail confirmation (as the default api.data.gov/signup page does), then we do not display the API key to them immediately. Instead, we only include the key in the e-mail to them, so effectively they have an account, but they can't use it until they receive the e-mail with the key. However, we do display the account ID to them on the signup confirmation screen for support purposes, so this is how someone could know their account ID, but not their key. Hope that clears up the mystery.

**Comment by brownpl** [comment]
Fantastic - thanks so much for the quick turnaround!
