### ISSUE TITLE
issues with custom date filtering 

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#477]
On the Filter Logs page in the admin panel, when I go to try and choose a custom date range, I can choose any date for the start date but only have Oct./Nov./Dec. and 2018/2019 available as choices for the end date.  

I'm using Chrome on OS X, but am wondering if it's local browser issues on my end.  @gui - are you able to replicate?

**Comment by GUI** [comment]
@gbinal: I believe additional end year dates will pop up, but only *after* you choose the starting date. For example, if you select "Custom Range," choose 2015 from the left-hand starting date area, and then click on a date in the left-hand calendar (to pick a specific starting date), then the right-hand calendar and year options should update to that same year and allow you to pick any date after the starting date as the ending date. But until you actually pick the starting date, the ending date year options will only reflect the current year.

This is related to some of the UI dependency updates recently made. One of those changes is an upgraded version of [Date Range Picker](https://github.com/dangrossman/daterangepicker), which changes some of the UI behavior. I'm not necessarily wild about some of the UI changes made, but I think they made them based on feedback about the previous behavior being confusing. Although, I do find this somewhat confusing too.

Let me know if picking the starting date fixes this for you. Although, even if it does, if we want to try to make this behave differently to be a bit more intuitive (since I do agree it's a bit confusing), I can look into making changes to this default behavior.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
