### ISSUE TITLE
error with the embedded signup form

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#484]
I'm trying to embed the signup form (code [here](https://github.com/GSA/open-gsa-redesign/blob/apidocs-datadotgov-20190214/_apidocs/datadotgov.md) - staging page [here](https://federalist-proxy.app.cloud.gov/preview/gsa/open-gsa-redesign/apidocs-datadotgov-20190214/api/datadotgov/)) but am getting this error message:  

<img width="750" alt="screen shot 2019-02-19 at 2 21 48 pm" src="https://user-images.githubusercontent.com/633088/53041405-e6c24f00-3451-11e9-946f-a380c7e0ec7e.png">

@gui - any thoughts what is wrong?

**Comment by GUI** [comment]
@gbinal: The API key being used on the signup form (`Wjww...`) had it's referrer restrictions set to `*//gsa.gov/*`. So it was rejecting these signup requests that were originating from this cloud.gov website. I went ahead and edited the API key to add this cloud.gov domain as an allowed referrer, so I believe it's working now, if you want to give it another spin.

That pesky empty bullet error message is something I should be able to fix (since there is a slightly more helpful error message being returned by the API). It's unfortunately been a long standing issue (#246), but it typically only shows up in these somewhat odd cases.

I also noticed the layout alignment of the label is a bit strange on this page. That's likely related to our default styles fighting with the GSA page's overall styles. Let me know if you want any help fixing that. We could either fix it with some custom styles on this specific GSA page, or alternatively, we could also update our embed code so this should work better by default, without any additional overrides. Since I think this is using the USWDS, it may be worth us updating the default styles of our widget to ensure better compatibility with other pages using the USWDS.

**Comment by gbinal** [comment]
Ah - quite right.  I'm sorry - it slipped my mind to think about it bering on a different domain like that.  

To the other point, yeah, I'll create an issue about updating the styles to either work better with USWDS or just be more generally friendly.
