### ISSUE TITLE
Add further fields in admin panel

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#490]
~For API Scopes:~
* ~Agency~
* ~Status~
* ~Alternate API Name~
* Related API Backends

For API Backends:
* Agency
* Status
* ~Alternate API Name~
* Related API Scopes

Note that these don't need to be connected (e.g. `agency` can independently set between the two.) 

What else?

**Comment by gbinal** [comment]
Great work on this so far, @nickm.  

One bug I've noticed is an a Datatables error.  On https://api.data.gov/admin/#/api_scopes, when I try to sort by the right two columns, I get this error:  

`DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

Using chrome.

**Comment by gbinal** [comment]
I x-ed out the requirements above that are no longer needed.

**Comment by GUI** [comment]
I've added new "Organization Name" and "Status" fields to the API backend form that are only available to superusers. These are free-form text fields, so you can put whatever you want in them, but this also means there's nothing to really enforce consistency (other than our own pedantry, so we'll probably be okay ;).

We may have not really talked in detail about how these new fields could be used for an updated metrics page, but I took an initial stab at hooking a few things up in the public metrics API so you can see how these fields will update summary counts: https://api.data.gov/api-umbrella/v0/analytics/summary.json There are new `api_backends.status_counts` and `api_backends.organization_count` fields. `api_backends.organization_count` will return a count of the number of unique "Organization Name" entries across all API backends. `api_backends.status_counts` will return an object that displays each "Status" field (eg, Production, Staging, etc) and the number of API backends associated with those.

I think it would be possible to shift both of these fields to API Scopes, which would result in less duplication and make some of this processing more automatic (since new API Backends would automatically inherit these fields from the closest API scope that the API backend belongs to). However, I know we've talked a bit about tying various things to the API scopes, and it does perhaps get a little more complicated in ensuring there are appropriate scopes setup and also understanding which scope would be inherited from. So instead, I added these 2 free-form fields directly onto the API backend form. But if we end up finding it to be a hassle to maintain these extra metadata fields, I'm just noting this scopes stuff as a potential alternative that might be more automatic.

I can bulk update these organization names and status fields if that's easier in any case (eg, I updated a bunch of NREL backends based on their name).

I also fixed a couple other smaller things while I was at it:

- The columns that display lists on the API scopes screen are no longer sortable, to fix that error you ran into.
- Fix the "Last Login" information missing from the admin group's listing of admins. This bug had cropped up during our initial database migration, but the information is now back.
- Fix the special "Superuser" group not being listed in the list of groups when viewing the list of admins.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
