### ISSUE TITLE
v1.1 edits to make the the metrics page

### ISSUE THREAD

**Issue by gbinal** [18F/api.data.gov#508]
* [x] add in a column after agency and before hits with 'Number of APIs' with the count of prefixes.  
* [ ] research total number of api keys vs. api keys used
* [x] round response time `ms` to the nearest whole number
* [x] address the odd spike in 2014
* [ ] move it onto api.data.gov/metrics (save for last) 
* [ ] add in legend language underneath (from Gray)
* [ ] add in link to API docs for this API
* [ ] add in # of api programs for gray to use for metrics

**Comment by GUI** [comment]
@gbinal: I think the bulk of this is deployed to the testing endpoint now. A few notes on remaining things:

- Can you let me know where you want to place the legend/explanation text? I can then point you in the right direction of where that can be inserted. I just wasn't sure if you wanted it below the charts, or down at the bottom below the table, or where.
- I still haven't really had a chance to fully dig into the API key counts, but I've been reviewing all the queries and I'm reasonably confident they're both sort of right, just different metrics. So I do believe that the closeness in numbers is a coincidence. They're actually more different now (118k vs 130k), since I'm now also excluding keys that have been disabled from our new usage metrics to remove some of the spam/spike traffic. The old signup metrics had already been excluding the disabled keys, so the fact that it dropped the active user metrics lower, despite the fact that they're now excluding similar keys, does seem to indicate that these are more separate.

  Again, I haven't fully dug into this to come up with more detailed and specific examples to verify all this, but the separate queries do seem to be correct from a high-level perspective. So I'm not sure if we really want to consider this done yet, or whether we want to really prove the metrics to ourselves by digging into a more specific timeframe in more detail (which could still be a useful sanity check, I think), but at a high-level I am at least more comfortable with what's going on.
- It will take me a bit longer to fully document all the parts of this new API, so I haven't added a link to that yet. We may also want to figure out how to caveat external people using it, since this is a "v0" API that we've had the luxury of being able to change to meet our specific needs, but if we start documenting it for external use, we'll probably need to be more careful about maintaining backwards compatibility. I think we can definitely get this documented, but I wasn't sure if you saw that as critical for the initial release, or whether that could come later.

**Comment by gbinal** [comment]
> Can you let me know where you want to place the legend/explanation text?

Sorry about that - below all of the metrics (both the chart and table) would be great.  If you just put in a word or two and I'm able to edit the page, I'll go back in and add text later.  

> So I'm not sure if we really want to consider this done yet, or whether we want to really prove the metrics to ourselves by digging into a more specific timeframe in more detail...

I'm comfortable with moving forward now.  Let's discuss more in the future, but thank you for gut-checking.  

> It will take me a bit longer to fully document all the parts of this new API, so I haven't added a link to that yet.  

Don't worry about that.  I don't feel the need to tie that with the release.  I'll probably take a crack at doing full documentation for it later and then will run it by you for feedback.  No need for you to do the heavy writing unless you are jones-ing to.

**Comment by GUI** [comment]
Okay, here's some footer text you can edit: https://github.com/18F/api.data.gov/blob/349560b3245583a401076220f7002e68f1b67eca/metrics/src/views/Metrics.vue#L44 It's in straight HTML (not markdown), hope that's okay. And I can help out styling it if you want.

And sounds good regarding the docs. We'll see who gets to it first. :) For future reference, here's the existing swagger spec for the admin docs that we could probably add this to: https://github.com/NREL/api-umbrella/blob/master/docs/_static/admin-api-swagger.yml

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
