### ISSUE TITLE
SAM Registration Endpoint times out (504), github.io docs return 404

### ISSUE THREAD

**Issue by CaseGuide** [18F/api.data.gov#595]
I've historically been able to use the endpoint at `api.data.gov/sam/v10/registrations/` however after a long period of not using it, today I am getting a 504 Gateway timeout and I note that the API docs previously hosted at https://gsa.github.io/sam_api/sam/ now return 404. 

EDIT: In searching google for a new endpoint I noted that the GitHub.com docs https://github.com/GSA/sam_api also 404. 

Has this endpoint and the documentation for it moved?

**Comment by VladimirAlexiev** [comment]
Second this: the list https://github.com/18F/api.data.gov/blob/master/source/docs/gsa.html.md points to https://gsa.github.io/sam_api/sam, but there's no repo https://github.com/GSA/sam_api, and I can't find any appropriate repo at https://github.com/GSA (over 800 repos).

Where art though, SAM?

**Comment by jbwachtel** [comment]
Can we get an update on this SAM connection? Our connection to the previous endpoint quit working and we have not been able to update it. The links provided seem to be broken.

**Comment by GUI** [comment]
Sorry everyone that this slipped past us.

I believe the SAM.gov team deprecated some of their endpoints recently in favor of their more recent APIs, which can be found at https://open.gsa.gov/api/.  

Just as a heads up, the SAM.gov team no longer employs the api.data.gov service, so if you have any trouble, the best way to reach out the SAM.gov team is to contact the Federal Service Desk (https://www.fsd.gov/) and open a service ticket. Describe your issue in detail so it can be assigned to the correct technical team for response.

Since SAM no longer users api.data.gov, I'm going to close this issue, but let us know if you have any other questions.
